### ISSUE TITLE
fix:Inconsistent terminology between "Sign Up" and "Sign In" on  Mobile Version

### ISSUE THREAD

**Issue by Helen-Sen** [BinaryStudioAcademy/bsa-2024-bebalance#109]
### Describe your issue

On the "Sign Up" page, the text reads "Go to Log In" (see screenshot), while the page itself is titled "Sign In," and the button on this page is also labeled "Sign In" (see screenshot). This inconsistency is present on the mobile versions of the page, which can confuse users.

### Steps to reproduce

1. Navigate to the "Sign up" page; 
2. Observe the link "Log In" (full text reads "Go to Log in");
3. Navigate to the "Sign in" page;
4. Observe the page title and button, both of which are labeled "Sign in."

### What was the actual result?

The "Sign Up" page contains the link "Log In." When the user clicks this link, they are directed to a page titled "Sign In," with a button also labeled "Sign In."

### What was the expected result?

The "Sign Up" page should consistently use the term "Sign In" instead of "Log In" to avoid confusion. The text should read "Go to Sign In."

### Put here any screenshots or videos (optional)

![Image](https://github.com/user-attachments/assets/13dda976-124a-410f-aa47-9d4675148273)

### What OS are you seeing the problem on?

Other (mention in the description)

### What browsers are you seeing the problem on?

Other (mention in the description)

### Severity

Minor (S4)

**Comment by ToyLess78** [comment]
The issue has been resolved in the latest PR.
<img width="301" alt="Знімок екрана 2024-08-31 о 16 18 45" src="https://github.com/user-attachments/assets/41887bf6-d685-4fef-80bb-7ba2031f5a95">
