### ISSUE TITLE
fix: User is not saved in redux store after sign in/sign up

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#118]
### Describe your issue

In auth slice, the user is saved incorrectly. The payload from Backend includes the token, but the Frontend does not take it into consideration

### Steps to reproduce

Open auth.slice.ts file on Frontend

### What was the actual result?

Instead of saving user, {user, token} object is saved (UserSignInResponseDto/UserSignUpResponseDto)

### What was the expected result?

We should save the user in slice (UserDto)
We should save the token in local storage

### What OS are you seeing the problem on?

Other (mention in the description)

### Severity

Major (S3)

**Comment by MarinaBershova** [comment]
The received token after Sign in/Sign up is saved in Local storage
