### ISSUE TITLE
feat: Custom RadioGroup component

### ISSUE THREAD

**Issue by anogire** [BinaryStudioAcademy/bsa-2024-bebalance#125]
### What feature?

- [x] Use `react-native-radio-buttons-group' library.
- [x] Create custom RadioGroup component.
- [x] Add a selection variant like on the frontend.

### Add screenshots

<img width="331" alt="Screenshot 2024-08-22 at 17 08 20" src="https://github.com/user-attachments/assets/3ebe0ab2-3fae-4f89-8fb3-c35fb7f450db">
<img width="359" alt="Screenshot 2024-08-22 at 17 08 34" src="https://github.com/user-attachments/assets/0eace967-589f-46c9-a691-d4c4ba938369">

**Comment by KotenkoNata** [comment]
I spent some time researching the react-native-radio-buttons-group library and came to the conclusion that it cannot meet our needs. It does not support gradient border and almost cannot be customized. Actually, it can, but then everything will remain only custom, and then nothing will remain from the library.
The maximum that can be done (without customizing) is at the bottom of the screen.


![Image](https://github.com/user-attachments/assets/cdf4ea09-c806-4246-bdbb-fe165b1588d9)


Do I understand correctly that I need this particular library? Was some other library intended (if so, I would be grateful for the link)?

**Comment by anogire** [comment]
I believe you can use this library. But if you want, you can implement the radio group function yourself.
And make the circle smaller, please.

**Comment by KotenkoNata** [comment]
Feature implemented as a part of the issue [feat: Onboarding screen #127](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/issues/127#issue-2480945332)
