### ISSUE TITLE
feat: BottomTab navigator

### ISSUE THREAD

**Issue by anogire** [BinaryStudioAcademy/bsa-2024-bebalance#128]
### What feature?

- [ ] Add BottomTab navigator.
- [x] Create blank screens for now.

### Add screenshots

<img width="731" alt="Screenshot 2024-08-22 at 17 33 24" src="https://github.com/user-attachments/assets/27877fca-9bbc-4226-9a96-d700c36ac801">

**Comment by LiudmylaPerev** [comment]
All 4 buttons have a different design from figma
1. Figma  ![Image](https://github.com/user-attachments/assets/8f6f7bda-896b-487d-814a-84875b97101e)
app  ![Image](https://github.com/user-attachments/assets/73eb027d-6bdc-4dcf-b0ef-82e7a8234947)

3. Figma ![Image](https://github.com/user-attachments/assets/5c9704db-c88a-4a44-8575-029b4d49123c)
app  ![Image](https://github.com/user-attachments/assets/09fb27bd-03ee-4b14-adf1-c08c89eaf499)

**Comment by Olha-Katran** [comment]
Replaced icon style from outline to regular 
![image](https://github.com/user-attachments/assets/fd2376a0-2b4f-4882-abb2-9bc5468852ae)

Regular: 
![image](https://github.com/user-attachments/assets/ee935fa1-6acd-47dd-b109-df63607d53ac)

**Comment by LiudmylaPerev** [comment]
in mobile, each icon will not have a separate colored rim and transparent middle, but instead a fully filled gradient across the entire area of the icon
