### ISSUE TITLE
fix: sign-in form markdown on web app

### ISSUE THREAD

**Issue by ihorLysak** [BinaryStudioAcademy/bsa-2024-bebalance#129]
### Describe your issue
On the "Sign In" page, inside of form container the markdown for the whole page is render inside of form container.

### Steps to reproduce
Navigate to "Sign in" Screen,
observe the whole page markdown being duplicated inside of form container.

### What was the expected result?
The sign in screen should look like sign up screen.

Put here any screenshots or videos (optional)

![Image](https://github.com/user-attachments/assets/050b0704-913a-4c5c-8bfc-9c9ce03da928)

### What OS are you seeing the problem on?
Other (mention in the description)

### What browsers are you seeing the problem on?
Other (mention in the description)

Severity
Minor (S4)

**Comment by phoebe-buffay** [comment]
issue is fixed. Sign In page looks correct

![Image](https://github.com/user-attachments/assets/12de2793-15f3-4cb3-8410-a13399017b94)
