### ISSUE TITLE
feat: Add Onboarding questions to DB

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#133]
### What feature?

- [ ] Create onboarding_questions table
- [ ] Create onboarding_answers table - should have a reference to onboarding_questions table
- [ ] Add following questions to DB

1. Question: "Can you tell me a bit about yourself? What’s currently important to you in your life?"
Options:
A. Family and relationships
B. Career and professional growth
C. Personal development and learning
D. Health and well-being
E. Financial stability

2. Question: "What are your key roles in life right now?"
Options:
A. Parent or caregiver
B. Professional or student
C. Partner or spouse
D. Friend or community member
E. Individual focused on personal growth

3. Question: "Do you have a partner?"
Options:
A. Yes
B. No

4. Question: "Which areas do you feel most challenged by right now?"
Options:
A. Balancing work and personal life
B. Maintaining healthy relationships
C. Managing stress and well-being
D. Pursuing personal goals or hobbies
E. Financial planning and stability

5. Question: "What specific outcomes would you like to see by using the app?"
Options:
A. Achieve a healthier lifestyle
B. Develop stronger connections with loved ones
C. Gain clarity in career direction
D. Improve financial planning
E. Enhance personal or spiritual growth

6. Question: "Are there any specific types of tasks or practices you enjoy or find particularly motivating?"
Options:
A. Reflective journaling
B. Physical exercise or wellness routines
C. Meditation or mindfulness practices
D. Creative activities (e.g., art, music)
E. Setting and achieving small goals

**Comment by LiudmylaPerev** [comment]
"Meditation or mindfulness practices" should be added to the onboarding_answers table

**Comment by LiudmylaPerev** [comment]
"Meditation or mindfulness practices" added
Need to check question "What's currently important to you in your life?"  on frontend
