### ISSUE TITLE
feat: Analyzing screen mobile responsiveness

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#136]
### What feature?

- [x] Add mobile responsiveness to this screen

### Add screenshots

![image](https://github.com/user-attachments/assets/ccec9a98-7f21-41c3-a31f-4851e015b301)

**Comment by MarinaBershova** [comment]
1. Up to 521px the title is not centered.
2. When the screen is reduced, the circles on the background intersect and the background does not look like on the mockup


![Image](https://github.com/user-attachments/assets/a16eecc2-3607-4391-ad52-46145489ae34)



![Image](https://github.com/user-attachments/assets/258b59c7-e38c-48f3-b5df-f3ffcf95a2eb)
