### ISSUE TITLE
feat: Get authenticated user

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#14]
- [x]  After refreshing the page, current user is received and saved in app state
- [x]  Use the token saved in localStorage to get current user and save that user to app state

**Comment by phoebe-buffay** [comment]
After refreshing the page, current user is received and saved in app state - is not working. After refreshing the page there is no request for the authenticated user. 



https://github.com/user-attachments/assets/2f62bc15-a8ab-409b-8435-56d634f31cc1
