### ISSUE TITLE
fix: Missing "Confirm password" field on the Sign-up page

### ISSUE THREAD

**Issue by Helen-Sen** [BinaryStudioAcademy/bsa-2024-bebalance#144]
### Describe your issue

When I try to create an account on the Sign-up page, there is no "Confirm password" field, but it must be according to requirement (see screenshot_2)

### Steps to reproduce

1. Navigate to the Sign-up page on the application (http://bebalance.eu-central-1.elasticbeanstalk.com/sign-up)
2. Observe the input fields available for creating an account (the field Confirm password is missing)Sign-up

### What was the actual result?

The "Confirm password" field is missing on the Sign-up page (see screenshot)

### What was the expected result?

I expected to see a "Confirm password" field so users can confirm their password before account creation.

### Put here any screenshots or videos (optional)

![image](https://github.com/user-attachments/assets/93c3aae4-41f9-4c3d-9d68-6842abc66d6e)
![image](https://github.com/user-attachments/assets/03c7c81c-0431-4bc9-ac2c-7d621a4a87b4)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

**Comment by phoebe-buffay** [comment]
The Confirm password field is added. The ticket can be closed. 

![Image](https://github.com/user-attachments/assets/2f96a54e-96d0-41e9-9841-2ee707f8ea04)

**Comment by phoebe-buffay** [comment]
also the issue was found with passwords which are don't match. this issue will be fixed in [#209](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/issues/209)

![Image](https://github.com/user-attachments/assets/24a0843f-31ec-487f-a4fb-ac05e969541c)
