### ISSUE TITLE
feat:Update z-index usage throughout the web app

### ISSUE THREAD

**Issue by MarinaBershova** [BinaryStudioAcademy/bsa-2024-bebalance#162]
### What feature?

Update z-index usage throughout the web app

**Comment by KeidsID** [comment]
Have audited all component CSS and each component has used the global `z-index`
in the "variables.css" file. So I don't know what PR to resolve this
since no changes are required.

**Comment by MarinaBershova** [comment]
z-index usage on sign-in and sign-up pages was updated in previously PRs

**Comment by KeidsID** [comment]
I reopened this issue since we had a z-index problem. I will create a PR to fix it.

![image](https://github.com/user-attachments/assets/7c6ca7af-85df-41a3-9ce9-a2f58c1cff1e)

**Comment by phoebe-buffay** [comment]
issue is fixed. ticket can be closed
