### ISSUE TITLE
feat: Save quiz response to DB

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#166]
### What feature?

- [x] Create an endpoint, which will save user responses for a quiz in a DB

Onboarding quiz will be handled separately

**Comment by luiqor** [comment]
Deatils of `Save quiz response to DB` tikcet tasks:
- [ ] quiz users' answers handling
`POST` `quiz/answer`

- [ ] adding scores fro users logic
Total score for category should be calculated as an average score (1-10) instead of sum

**Comment by phoebe-buffay** [comment]
endpoint works correct, answers are saved. ticket can be closed
