### ISSUE TITLE
fix: move getAuthenticated user action to auth redux store

### ISSUE THREAD

**Issue by marharita08** [BinaryStudioAcademy/bsa-2024-bebalance#171]
### Describe your issue

getAuthenticatedUser action was added to a wrong redux store.

### Steps to reproduce

Open auth.slice.ts and users.slice.ts files on Frontend

### What was the actual result?

signIn and signUp actions save user to auth state.
getAuthenticatedUser action saves user to users state.

### What was the expected result?

signIn, signUp and getAuthenticatedUser actions should save user in the same place.

### What OS are you seeing the problem on?

Windows

### Severity

Major (S3)

**Comment by LiudmylaPerev** [comment]
when an authenticated user reloads the page, user should remain authenticated
