### ISSUE TITLE
feat: Add a possibility to update profile picture

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#173]
### What feature?

We need a new endpoint, where the user will be able to upload a new profile avatar. The avatar will be uploaded to AWS S3 bucket. We need a new table - files, and a new field in user_details table - avatarFileId

**Comment by MarinaBershova** [comment]
1. Change the endpoint in the Swagger to users/avatar
2. Image not available via link in response

**Comment by phoebe-buffay** [comment]
1. Change the endpoint in the Swagger to users/avatar - done
2. Image not available via link in response - done
https://github.com/user-attachments/assets/197806bc-e084-44f0-853d-1864f9ff5295
3.  table - files - done ![Image](https://github.com/user-attachments/assets/f72fe5e6-2bf9-4afe-a025-ee7fdb8c49dd)

4. new field in user_details table - avatarFileId - done ![Image](https://github.com/user-attachments/assets/b6e31de4-3365-4267-acdf-390197fafacc)
