### ISSUE TITLE
feat: Checkbox component

### ISSUE THREAD

**Issue by anogire** [BinaryStudioAcademy/bsa-2024-bebalance#174]
### What feature?

- [x] Create custom Checkbox component.
- [x] Add styles.
- [x] Try [`@react-native-community/checkbox`](https://www.npmjs.com/package/@react-native-community/checkbox) or [react-native-checkbox-reanimated](https://github.com/craftzdog/react-native-checkbox-reanimated) libraries. Choose the appropriate one.

### Add screenshots

<img width="599" alt="Screenshot 2024-08-24 at 18 03 31" src="https://github.com/user-attachments/assets/8834cc7e-5463-4312-8155-4dca4490b85d">

**Comment by ToyLess78** [comment]
1. Should the component be named `CustomCheckbox` or something else?
2. What are the required props that `CustomCheckbox` should accept?
3. In which component of the application should I use the `CustomCheckbox`?
4. What is the deadline for this task?

**Comment by revenets** [comment]
> 1. Should the component be named `CustomCheckbox` or `Checkbox`?
> 2. What are the required props that `Checkbox` should accept?
> 3. In which component of the application should I use the `Checkbox`?
> 4. What is the deadline for this task?

1. Just Checkbox
2. Props: label - optional, isChecked, and all the props to use it in a form
3. The Checkboxes will be used on the Chat screen
4. As for every task on this project - ASAP =)
