### ISSUE TITLE
feat: User profile screen

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#187]
### What feature?

Add User profile screen, where we will display user data (/profile route)
User should also be able to update data - currently only name
There's no design, so do something similar to a general app design

**Comment by phoebe-buffay** [comment]
the  user profile screen works correct. ticket can be closed

https://github.com/user-attachments/assets/9143e11b-bb9b-4b30-9ab6-7418c3559ccb
