### ISSUE TITLE
fix: update breakpoint on quiz introduction screen

### ISSUE THREAD

**Issue by marharita08** [BinaryStudioAcademy/bsa-2024-bebalance#199]
### Describe your issue

quiz introduction page has different breakpoint than sign in and sign up pages

### Steps to reproduce

open styles.module.css files for sign in, sign up and quiz introduction pages

### What was the actual result?

quiz introduction page has different breakpoint than sign in and sign up pages

### What was the expected result?

breakpoints should be the same on every page

### What OS are you seeing the problem on?

Windows

### Severity

Minor (S4)

**Comment by Helen-Sen** [comment]
All pages (Sign In, Sign Up, and Quiz Introduction) share the same 768px breakpoint.
