### ISSUE TITLE
feat: Sign In

### ISSUE THREAD

**Issue by anogire** [BinaryStudioAcademy/bsa-2024-bebalance#20]
- [x]  Sign in form
- [x]  Sign in action flow
- [x]  Add user to redux store
- [x]  Validation (shared)
- [x]  "Create an account" link should navigate to the sign up page

**Comment by MarinaBershova** [comment]
The "Sign in" button responds only after tapping on it twice



https://github.com/user-attachments/assets/74d4ff10-839a-4122-88ff-860806b8c0ab

**Comment by MarinaBershova** [comment]
The "Sign in" button responds after the first tap
