### ISSUE TITLE
feat: AI Integration

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#203]
### What feature?

- [ ] Add integration with OpenAI
- [ ] We should send user responses within a prompt
- [ ] We should ask OpenAI to give a task for a specific category. Categories will be selected by a user
- [ ] Create a new tasks table and save a task there. A task should have a label, description, categoryId, userId and status
- [ ] Status can be Current, Skipped, Completed

We need to send user's responses for onboarding questions in a prompt, so that we get personalized response.

**Comment by phoebe-buffay** [comment]
feature works. ticket can be closed
