### ISSUE TITLE
feat: Balance Wheel animation

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#204]
### What feature?

We should have a Balance Wheel component, which will be animated
By animation we mean each part of the wheel should move
Use [this library](https://www.chartjs.org/docs/latest/charts/polar.html)

### Add screenshots

![image](https://github.com/user-attachments/assets/b6c0288b-efda-46e6-9bd1-f6946a7e9399)

**Comment by JD-Rosales** [comment]
Can I use react [https://www.npmjs.com/package/react-chartjs-2](url) on top of the chartjs library?

**Comment by MarinaBershova** [comment]
Need to add background and animated text "Analyzing"

![Image](https://github.com/user-attachments/assets/03d1503a-0ebe-4a71-92b4-d10d51f4cbae)

**Comment by MarinaBershova** [comment]
Make the percentages the same as in the mobile version, add 13%, 38%, 63%, 88%

https://github.com/user-attachments/assets/c1a55258-aeae-454a-94b7-24a78847aae0

**Comment by MarinaBershova** [comment]
Please add "Analyzing 100%" item as it is currently missing and after 88% a user account is opened

https://github.com/user-attachments/assets/e9869953-ca50-486a-9ab5-759bfec28f14

**Comment by phoebe-buffay** [comment]
as far as i understand, [351](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/pull/351) handle the whole flow. The issue mentioned above _"Please add "Analyzing 100%" item as it is currently missing and after 88% a user account is opened"_ is still present. please fix

**Comment by Helen-Sen** [comment]
Comment from @revenets: During the analysing animation on sometimes the wheel is truncated, so we need to add some extra paddings to it. Take a look at the blue sections’ border. 
![image](https://github.com/user-attachments/assets/78a4017d-3786-4d55-bd95-9a9b781231d9)

**Comment by phoebe-buffay** [comment]
please, take a look at the comment above
when the part of the wheel become the biggest, their borders become cut
https://github.com/user-attachments/assets/cbc2c9f7-7d71-42c5-9595-ea7396e8d978

**Comment by phoebe-buffay** [comment]
the issue with the borders is fixed
the issue with percents is fixed
ticket can be closed
https://github.com/user-attachments/assets/f818da3f-9e90-421b-8231-3f6f28037ac0
