### ISSUE TITLE
feat(web):Requirements for Authorization pages for web version

### ISSUE THREAD

**Issue by Helen-Sen** [BinaryStudioAcademy/bsa-2024-bebalance#209]
### What feature?

Full document: https://docs.google.com/document/d/1rPGvjFAN-btXFY8yAoVGRwwcf0D70u_BS36lcyRYh-8/edit?usp=sharing
Summary info for devs about authentification: https://docs.google.com/document/d/1dSfd2NyLqzaL0Dwiu6w2KS73t9QwB-S4_Pb3gMvBwG0/edit?usp=sharing

**Comment by MarinaBershova** [comment]
For Sign up page:
1. Remove extra hint under "Email" field
2. Add the ability to use hyphen in the local part of email


![Image](https://github.com/user-attachments/assets/cd8773ad-9896-49a6-aa03-9a29a3aa4d9e)

3. Remove extra space between field and message


![Image](https://github.com/user-attachments/assets/f88898aa-f1bf-4d97-a1fa-a95b86547e11)

4. "Name" field should not accept data containing a space (for example, John Smith - such an entry is prohibited)


![Image](https://github.com/user-attachments/assets/c8d1c085-4f30-406c-b7a6-cc8e1c9bb6b4)

5. The minimum length domain part of email should be 3 symbols

![Image](https://github.com/user-attachments/assets/e5bb4b1e-9b1d-4ace-b1bd-c8071bc17dd7)

6. Add validation for max allowed email length - [35 symbols]@[35 symbols].com
7. An error message should appear if a user attempts to register using an already registered email address


https://github.com/user-attachments/assets/354bb823-b94a-46e4-ba46-92d59a8e03dc

8. If the user enters Cyrillic letters in the "Password" field, should appear a message "Your password contains invalid characters. Only letters, numbers, and ! @ # $ symbols are allowed."

![Image](https://github.com/user-attachments/assets/d6f55651-c8d6-4594-9dbb-b7dc2bf53921)

**Comment by MarinaBershova** [comment]
Sign in page:
1. Remove extra hint under "Email" field


![Image](https://github.com/user-attachments/assets/829cdf74-c3d9-4ca9-ae9e-2211f5187fa0)

2. Add validation for max allowed email length - [35 symbols]@[35 symbols].com
3. An error message “Invalid email or password” should appear if a user attempts to Sign in with email or password which dosen't match with data in DB


https://github.com/user-attachments/assets/47f6e03d-25b1-4138-b62a-70e45e44adff

**Comment by MarinaBershova** [comment]
For Sign up page:
1. Add the ability to use hyphen in the local part of email (for ex. Mickey-mouse@example.com)
2. The minimal valid length of email should be - [1 symbol]@[4 symbols]
3. The maximal valid length of email should be - [35 symbols]@[35 symbols]

**Comment by phoebe-buffay** [comment]
1. Add the ability to use hyphen in the local part of email  -  passed
2. The minimal valid length of email should be - [1 symbol]@[4 symbols] - passed
3. The maximal valid length of email should be - [35 symbols]@[35 symbols] - passed
