### ISSUE TITLE
feat: Categories selection component

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#220]
### What feature?

- [x] Get categories from Backend
- [x] Create a component for selecting categories

### Add screenshots

![image](https://github.com/user-attachments/assets/f5362557-4143-4dee-bab8-f159778c1a3a)

**Comment by KeidsID** [comment]
![Screenshot (329)](https://github.com/user-attachments/assets/52618517-cc79-41f0-b9bb-b91c1aa4b846)

**Comment by fshabanov** [comment]
@KeidsID you should create a new module/slice for that

**Comment by phoebe-buffay** [comment]
component is working correct, the ticket can be closed
https://github.com/user-attachments/assets/c2b848f9-ea79-4f11-955e-6cde7e5c1fbc
