### ISSUE TITLE
fix:An error messages appear on Sign in page

### ISSUE THREAD

**Issue by MarinaBershova** [BinaryStudioAcademy/bsa-2024-bebalance#224]
### Describe your issue

An error messages appear on Sign in page when try to open this page

### Steps to reproduce

1. Go to http://bebalance.eu-central-1.elasticbeanstalk.com/sign-in
2. Pay attention to the error messages that appear

### What was the actual result?

An error message appeared

### What was the expected result?

An error message dosn't appear

### Put here any screenshots or videos (optional)

![2024-08-28_11h52_21](https://github.com/user-attachments/assets/6a731d30-a1a1-4cfb-8a8a-e8cd6ec90bc8)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

**Comment by MarinaBershova** [comment]
duplicate of https://github.com/orgs/BinaryStudioAcademy/projects/29/views/1?filterQuery=sign+&pane=issue&itemId=76766033

**Comment by LiudmylaPerev** [comment]
duplicate of tickethttps://github.com/BinaryStudioAcademy/bsa-2024-bebalance/issues/222
