### ISSUE TITLE
fix: wrap quiz component into protected route

### ISSUE THREAD

**Issue by marharita08** [BinaryStudioAcademy/bsa-2024-bebalance#234]
### Describe your issue

Not authenticated user can open quiz page.

### Steps to reproduce

Being not authenticated open /quiz path.

### What was the actual result?

Page opens.

### What was the expected result?

Shold redirects on sign-in page.

### What OS are you seeing the problem on?

Windows

### Severity

Minor (S4)

**Comment by MarinaBershova** [comment]
An unauthorized user is redirected to the Sign in page if he try to open http://bebalance.eu-central-1.elasticbeanstalk.com/quiz
