### ISSUE TITLE
feat: Onboarding/quiz flow

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#242]
### What feature?

- [x] Connect Onboarding, Quiz and other components to have a proper flow
- [x] After registration the user should see Onboarding questions (only if they haven't passed the quiz yet)
- [x] After Onboarding, the user should see "Analyzing" screen
- [x] After "Analyzing" screen, the user should see Quiz introduction screen
- [x] After Quiz introduction, the user should see Quiz screen
- [x] After Quiz screen, the user should see the screen with final questions about notifications
- [x] Then we display the loading animation with an animated wheel component
- [x] Save onboarding and quiz answers to the Backend

**Comment by Mikoyzskie** [comment]
- After Quiz screen, the user should see the screen with final questions about notifications

question about this one...
Where can I find these final questions about notifs?
