### ISSUE TITLE
feat: Final questions screen

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#243]
### What feature?

This is a Full-Stack task, both Backend and Frontend should be implemented

- [ ] Create a table to save the days of the week, when the user wants to get new tasks (we will save the number of the day: Monday = 1, Tuesday = 2, etc.)
- [ ] Add a new boolean field to user_details to save if the user allowed notifications
- [ ] Create a view as in the design
- [ ] For notifications, only first and last point should be added for now (first = true, last = false)
- [ ] Save the user's response to the Backend

### Add screenshots

![final](https://github.com/user-attachments/assets/f634d686-1945-4026-8a21-72a4fca4e7f4)

**Comment by MarinaBershova** [comment]
Add validation for "userTaskDays" array


![Image](https://github.com/user-attachments/assets/388d27b7-8163-4f3b-aa4b-8e2e7a7f8447)

**Comment by phoebe-buffay** [comment]
The "?" in the first question will be added by @yulyaolshanska

**Comment by MarinaBershova** [comment]
The answer to the second question should be "Yes, I'd love  daily motivation" by default.
