### ISSUE TITLE
feat: Quiz screen

### ISSUE THREAD

**Issue by anogire** [BinaryStudioAcademy/bsa-2024-bebalance#245]
### What feature?

- [x] Create Quiz screen.
- [x] Reuse our RadioGroup component for answers.
- [x] Create counter (you can add animation).
- [x] When you select the answer to the last question - you go to the “Analyzing” screen.

### Add screenshots

<img width="363" alt="Screenshot 2024-08-30 at 09 08 13" src="https://github.com/user-attachments/assets/d2e06ea4-7eb9-4395-87f1-e41b1bd8e7e2">

**Comment by KotenkoNata** [comment]
- Do I need to redirect the user to another screen after the quiz?

 - Should this screen have BACK and NEXT buttons as on the web version and the Onboarding screen?

![Image](https://github.com/user-attachments/assets/a5446122-aaf0-4c65-86d6-5e20bf66837f)
![Image](https://github.com/user-attachments/assets/0fb41574-89df-4af3-b93e-456a476509fe)

**Comment by KotenkoNata** [comment]
We decided to keep navigation buttons at the bottom of screen.
