### ISSUE TITLE
fix:Problem with loading Sign in, Sign out pages for authorized user

### ISSUE THREAD

**Issue by Helen-Sen** [BinaryStudioAcademy/bsa-2024-bebalance#246]
### Describe your issue

When the user try to open Sign in and Sign out pages these pages appear in milliseconds and the user is automatically redirected to the root page

### Steps to reproduce

1. Navigate to http://bebalance.eu-central-1.elasticbeanstalk.com/sign-in
2. After some milliseconds you are automatically redirected to the root page.
3. Navigate to http://bebalance.eu-central-1.elasticbeanstalk.com/sign-up
4. After some milliseconds you are automatically redirected to the root page.

### What was the actual result?

When the authorized user tries to open Sign in, Sign out pages these pages appear in milliseconds and the user is automatically redirected to the root page.

Note: As an unauthorized user (another browser or incognito page) I can open Sign in, Sign out pages.

### What was the expected result?

When I, as an authorized user, go to the Sign in or  Sign up pages, I should be automatically redirected to the root page without flashing the Sign in or  Sign up pages. 
If the authorization token has expired, the user should navigate  to the requested page

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/a60e2657-1306-4dce-8c46-4ccba70a5bdc

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

**Comment by MarinaBershova** [comment]
When an authorized user tries to open Sign in or Sign up page, only a loader is displayed for milliseconds and the user redirected to the root page
