### ISSUE TITLE
feat: Button component

### ISSUE THREAD

**Issue by anogire** [BinaryStudioAcademy/bsa-2024-bebalance#26]
- [x] Create a common Button component
- [x] Add `appearance` prop ('filled', 'outlined' - `filled` is default) and define buttons' style based on it

**Comment by Shcracoziabra** [comment]
The Button component already exists, should I apply changes to it?

**Comment by revenets** [comment]
> The Button component already exists, should I apply changes to it?

Yes. edit the existing one

**Comment by revenets** [comment]
You'll probably need to install `react-native-linear-gradient` for buttons' pressed style
