### ISSUE TITLE
feat:Create test cases for sign in page

### ISSUE THREAD

**Issue by Helen-Sen** [BinaryStudioAcademy/bsa-2024-bebalance#271]
### What feature?

Create test cases that cover authorization for sign in page (http://bebalance.eu-central-1.elasticbeanstalk.com/sign-in): both negative and positive scenario

Create test cases that cover authorization for sign in page for mobile version
Location: https://app.qase.io/project/BEBALANCE

**Comment by StanislavHorkusha** [comment]
@Helen-Sen I recommend not using specific emails/usernames/etc when we test invalid (non-existent) user sign-in. Anyone can create a user with the same credentials that you mentioned (e.g. in BEBALANCE-60) and it will cause the TC to fail upon next run
