### ISSUE TITLE
fix: onboarding/answer and quiz/answer endpoints are failing and show error 

### ISSUE THREAD

**Issue by phoebe-buffay** [BinaryStudioAcademy/bsa-2024-bebalance#286]
### Describe your issue

onboarding/answer and quiz/answer endpoints from Swagger side are failing and show error "You are unauthorized to access the requested resource."

### Steps to reproduce

1. Enter swagger, sign in and authorize
2. try out ondoarding/answer and quiz/answer endpoints (answerId 107)
3. observe the response

### What was the actual result?

{
  "errorType": "COMMON",
  "message": "You are unauthorized to access the requested resource."
}

### What was the expected result?

User should receive the correct response, as they are already have made the authorization

### What OS are you seeing the problem on?

MacOS

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

**Comment by KeidsID** [comment]
My #266 PR will fix this issue. Its just missing authorization on the swagger.

**Comment by phoebe-buffay** [comment]
the issue is fixed, the ticket can be closed
![Image](https://github.com/user-attachments/assets/4b848c50-13f9-4e63-8148-34126d65fb75)
![Image](https://github.com/user-attachments/assets/c4824239-f47e-448d-8c37-21ad8168813e)
