### ISSUE TITLE
feat: Onboarding questions screen mobile responsiveness

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#289]
### What feature?

- [ ] Add mobile responsiveness to Onboarding questions screen

**Comment by MarinaBershova** [comment]
At resolution 480px:
1. Change border size of answer options (answers should be on one line) according to design
2. Сenter answer options


![Image](https://github.com/user-attachments/assets/8a7121a4-4c6f-4d85-bd2f-2748dc102726)



![Image](https://github.com/user-attachments/assets/ba502d33-22d7-4d57-a150-a288ca83f479)

3. Change size of "Back" and "Next" buttons according to design


![Image](https://github.com/user-attachments/assets/0253487b-5526-4069-8d83-b4abca88b07f)

At resolution 768px:
1. This answer must be on one line and centered


![Image](https://github.com/user-attachments/assets/11baf7b9-fe65-4665-9105-c659f310035c)

**Comment by MarinaBershova** [comment]
All issues have been fixed
