### ISSUE TITLE
feat: Quiz questions screen mobile responsiveness

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#290]
### What feature?

- [x] Add mobile responsiveness to Quiz questions screen

**Comment by MarinaBershova** [comment]
At resolution from 480px to 768px:
1. Change the size of the border around the answer options according to design


![Image](https://github.com/user-attachments/assets/b09a6c49-341d-4ec4-8f91-021bdf5448ff)


in Figma:
![Image](https://github.com/user-attachments/assets/90846589-46b9-444d-b797-9494477f5f7f)

2. Change size and position of buttons ("Next" under "Back")
in Figma:


![Image](https://github.com/user-attachments/assets/0a8aaa88-bcf2-406c-9284-4167dbbf608a)

3. When user clicks on the button "Back"/"Next", the previous/next page should automatically scroll up

**Comment by MarinaBershova** [comment]
Remove hover state from the buttons on mobile responsiveness

https://github.com/user-attachments/assets/6ac7ac7e-bc56-4c02-b52c-027e7d9f0f93

**Comment by marharita08** [comment]
> Remove hover state from the buttons on mobile responsiveness
> 
>  2024-09-13.111014.mp4

fshabanov said that it is normal behavior.

**Comment by phoebe-buffay** [comment]
When user clicks on the button "Back"/"Next", the previous/next page should automatically scroll up - corrected. 
ticket can be closed
https://github.com/user-attachments/assets/afffcddf-4bfa-4ade-9bd0-8d81e71d8b1b
