### ISSUE TITLE
feat: Move "Sign out" button from Sidebar to Settings - Request from PO

### ISSUE THREAD

**Issue by Helen-Sen** [BinaryStudioAcademy/bsa-2024-bebalance#308]
### What feature?

Currently, the "Sign Out" button is located at the bottom of the sidebar. As per the product owner's request, it should be moved into the "Settings" section.

Requirements:
1. Relocate the "Sign Out" button from the sidebar to the "Settings".
2. Ensure that the button remains fully functional after relocation.

**Comment by phoebe-buffay** [comment]
For the design use please ticket [417](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/issues/417 )

**Comment by iqbalalayubbi** [comment]
This ticket title is not relevant to the design because we should move the sign out button from the sidebar to profiles, not settings

![Image](https://github.com/user-attachments/assets/e90a1107-b949-4341-a80b-d1ee962108d1)

**Comment by phoebe-buffay** [comment]
the ticket can be closed as the enhancement will be done in [#417](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/issues/417)
