### ISSUE TITLE
fix:There is extra space between label and field on Sign in, Sign up, Forgot password pages 

### ISSUE THREAD

**Issue by MarinaBershova** [BinaryStudioAcademy/bsa-2024-bebalance#312]
### Describe your issue

There is extra space between label and field on Sign in, Sign up, Forgot password pages 

### Steps to reproduce

1. Go to http://bebalance.eu-central-1.elasticbeanstalk.com/sign-in
2. Pay attention to the labels and fields
3. Go to http://bebalance.eu-central-1.elasticbeanstalk.com/sign-up
4. Pay attention to the labels and fields
5. Go to http://bebalance.eu-central-1.elasticbeanstalk.com/forgot-password
6. Pay attention to the labels and fields

### What was the actual result?

There is extra space between labels and fields

### What was the expected result?

There is no extra space between labels and fields

### Put here any screenshots or videos (optional)

![2024-09-05_18h23_36](https://github.com/user-attachments/assets/97dec365-bf76-439c-af5f-522fb0676db7)
![2024-09-05_18h28_17](https://github.com/user-attachments/assets/cbb298f6-3fce-4ca8-b1f3-6a8d7a47ebca)
![2024-09-05_18h29_04](https://github.com/user-attachments/assets/8a67aa0a-cb84-4ba6-bbf9-dd55d014045e)
Labels and fields should be indented like here:
![2024-09-05_18h42_25](https://github.com/user-attachments/assets/0f771d76-2eee-4c8d-8a1a-98afdfa82785)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

**Comment by Helen-Sen** [comment]
Now the bug is fixed, no extra spaces between labels and fields on Sign in, Sign up, Forgot password pages
