### ISSUE TITLE
feat: Create a task card

### ISSUE THREAD

**Issue by anogire** [BinaryStudioAcademy/bsa-2024-bebalance#321]
### What feature?

- [ ] Create an active/past switch.
- [ ] Extend the existing Button component. Let's use accessoryLeft/accessoryRight instead of icon props.
- [ ] Create a CountdownTimer component (days : hours : minutes). You can leave it just as a static image for now.
- [ ] <img width="51" alt="Screenshot 2024-09-06 at 09 56 17" src="https://github.com/user-attachments/assets/d8bf71c4-8eb3-467c-9481-7757ec062b9e"> - Leave it just as a static image for now too.
- [ ] Combine all elements into the "Task Card" component.
- [ ] Add logic to display cards in Active/Past state on the "Tasks" screen.

### Add screenshots

- [ ] <img width="209" alt="Screenshot 2024-09-06 at 09 52 39" src="https://github.com/user-attachments/assets/297fb217-0f30-4138-aaf4-9556cc1e1442">

- [ ] <img width="111" alt="Screenshot 2024-09-06 at 15 01 31" src="https://github.com/user-attachments/assets/7e609016-797d-4226-8f56-2ab32bb82c68"> <img width="138" alt="Screenshot 2024-09-06 at 15 01 40" src="https://github.com/user-attachments/assets/2542d99d-d507-4d11-8e11-d8b8d8f8ec28"> <img width="281" alt="Screenshot 2024-09-06 at 15 01 51" src="https://github.com/user-attachments/assets/edefe532-c98e-4042-98de-081303feea05">

- [ ] <img width="111" alt="Screenshot 2024-09-06 at 09 53 34" src="https://github.com/user-attachments/assets/b8c376dc-02ee-40f3-acaa-86a2c93b2323">

- [ ] <img width="333" alt="Screenshot 2024-09-06 at 14 56 56" src="https://github.com/user-attachments/assets/aaa819bf-a924-478c-a46a-1c25b613182f">

**Comment by KotenkoNata** [comment]
Hi, in the slack discussed changes to timer - [here](https://bsa2024.slack.com/archives/C07HBKZFCF2/p1726328203313419) you can have a look
