### ISSUE TITLE
fix(web): "Forgot Password" link on the Sign in page has an incorrect font size.

### ISSUE THREAD

**Issue by Helen-Sen** [BinaryStudioAcademy/bsa-2024-bebalance#331]
### Describe your issue

As per the Figma design specifications, the "Forgot Password" link on the Sign-In page should have a font size of 16px. Currently, the font size is set to 14px, which does not match the design.

Note:  "Create an account" link has a 16px font size, which causes a noticeable aesthetic inconsistency between the two links.

### Steps to reproduce

1. Navigate to the Sign In page (http://bebalance.eu-central-1.elasticbeanstalk.com/sign-in).
2. Locate the "Forgot Password" link.

### What was the actual result?

The "Forgot Password" link is displayed with a 14px font size.

### What was the expected result?

The "Forgot Password" link should have a font size of 16px as per the design.

### Put here any screenshots or videos (optional)

actual: ![image](https://github.com/user-attachments/assets/f58132e0-d664-4b86-8f87-845b7aca1d8e)
expected: 
![image](https://github.com/user-attachments/assets/aefe0160-a275-431d-a074-ff5cf4af9b4f)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

**Comment by MarinaBershova** [comment]
The “Forgot Password” link has a font size of 16px


![Image](https://github.com/user-attachments/assets/d48a5df0-eab9-4a29-9de1-b6c5fbf95326)
