### ISSUE TITLE
feat: AI Chat

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#340]
### What feature?

After completing all questions after the registration, the user needs to be redirected to the chat with initial question
Initially the categories with 3 lowest values should be selected
Send selected categories to AI and display the suggested tasks for the user

### Add screenshots

<img width="712" alt="image" src="https://github.com/user-attachments/assets/c9d740e1-fc78-48f8-b1fa-4ace26238ee8">

**Comment by ihorLysak** [comment]
Test whether chat generates the suggestions for three lowest categories and for categories that were selected by user. If everything works fine, i suppose you should return this issue to "in progress" column since there will be more features later
