### ISSUE TITLE
feat: Upload a new avatar

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#341]
### What feature?

From user profile screen, user needs to upload a new avatar. The form for avatar will be separated from the form of updating the user details.
Use real user avatar in all other places as well (example: header)

**Comment by MaxKorop** [comment]
1. I think there is no required size in pixels for the avatar image
2. Supported image formats PNG, JPG
3. The strict file size limit is 1 MB but there is no recommended limit to ensure quick load times
4. No, the user won't be notified
