### ISSUE TITLE
fix(mobile): "Forgot password" link is missing on the Sign In page.

### ISSUE THREAD

**Issue by Helen-Sen** [BinaryStudioAcademy/bsa-2024-bebalance#349]
### Describe your issue

The "Forgot password" link is not present on the Sign In page. According to the design, it should be displayed below the "Sign In" button (see screenshot)

### Steps to reproduce

1. Open the app on a mobile device.
2. Navigate to the Sign In page.
3. Observe that the "Forgot password" link is missing below the "Sign In" button.

### What was the actual result?

The "Forgot password" link is not present on the Sign In page.

### What was the expected result?

The "Forgot password" link should be present on the Sign In page as per the design.

### Put here any screenshots or videos (optional)

design: 
![image](https://github.com/user-attachments/assets/ada9575c-0e5c-4bf8-a094-5b315ad0bb52)
actual result: 
![image](https://github.com/user-attachments/assets/c499ef1a-37b0-4b1c-a52d-18874a987134)

### What OS are you seeing the problem on?

Android

### What browsers are you seeing the problem on?

Other (mention in the description)

### Severity

Major (S3)

**Comment by StanislavHorkusha** [comment]
Only assign yourself if you're doing [358](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/issues/358)
