### ISSUE TITLE
feat: Forgot password functionality

### ISSUE THREAD

**Issue by anogire** [BinaryStudioAcademy/bsa-2024-bebalance#358]
### What feature?

- [x] Add "Forgot password" link to the Sign In page.
- [x] Use **send email** and **deeplink** to take the user to a form with a changed password.
- [x] Save the changed password and take the user to the Sign In screen for authorization.

**Comment by StanislavHorkusha** [comment]
Please, assign [349](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/issues/349) to yourself too upon doing this task

**Comment by phoebe-buffay** [comment]
The improvement about UI and text changes was made in the [ticket](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/issues/422). Please, pay attention

**Comment by Shcracoziabra** [comment]
#500
