### ISSUE TITLE
feat:Add Intro motivation screen

### ISSUE THREAD

**Issue by MarinaBershova** [BinaryStudioAcademy/bsa-2024-bebalance#377]
### What feature?

- [ ] After successful registration user shold see "Intro motivation screen" and after clicking the "Let's start" button, go to the page with Onboarding questions

![2024-09-10_15h23_51](https://github.com/user-attachments/assets/1d273f14-9234-47b8-8415-b07fbc11bf6c)

**Comment by Helen-Sen** [comment]
After successful registration, I redirect to the root page (http://bebalance.eu-central-1.elasticbeanstalk.com/). But I should be redirected to http://bebalance.eu-central-1.elasticbeanstalk.com/onboarding.
