### ISSUE TITLE
feat(web): Standardize checkbox design across all pages

### ISSUE THREAD

**Issue by Helen-Sen** [BinaryStudioAcademy/bsa-2024-bebalance#415]
### What feature?

Standardize checkbox design across all pages to ensure uniformity. The checkmark style and background should follow the specified design as shown in the attached screenshot.

### Add screenshots

![image](https://github.com/user-attachments/assets/db177ecd-9eb5-4bb4-b4d0-c398ee4a29f3)

**Comment by phoebe-buffay** [comment]
checkbox element is tested on the available pages and looks correct
![Image](https://github.com/user-attachments/assets/11b8258f-5d0f-4238-a5eb-e6c889834f79)
![Image](https://github.com/user-attachments/assets/ebf8d1eb-0481-4ee4-8f2b-5ddf6195d3c3)
