### ISSUE TITLE
feat: Add logo to mobile app

### ISSUE THREAD

**Issue by anogire** [BinaryStudioAcademy/bsa-2024-bebalance#423]
### What feature?

- [x] Add to screens (signIn, signUp, ...).
- [x] Make an icon for the application.
- [x] Add to SplashScreen.

**Comment by KotenkoNata** [comment]
Should looks like for web version?

![Image](https://github.com/user-attachments/assets/12ca3946-1608-43b2-a8c7-3ca5edbc3bf2)

**Comment by anogire** [comment]
Yeah, let's do the same thing.
A SplashScreen could look like this: 
<img width="306" alt="Screenshot 2024-09-14 at 12 57 34" src="https://github.com/user-attachments/assets/80b8945d-07d9-49f1-8847-214180655c22">

**Comment by KotenkoNata** [comment]
Maybe leave our background and with the logo, it can look as below?

![Image](https://github.com/user-attachments/assets/7843da1c-78c7-4651-85bf-490804c0de98)

**Comment by revenets** [comment]
I'm that we'll be able to do this regarding android requirements to the splash 
[https://developer.android.com/develop/ui/views/launch/splash-screen](https://developer.android.com/develop/ui/views/launch/splash-screen)

**Comment by KotenkoNata** [comment]
Decided to create SplashScreen and icon as below

![Image](https://github.com/user-attachments/assets/83ac5ee4-6f5f-46d5-b7c3-f9c9a2c6cf58)


![Image](https://github.com/user-attachments/assets/38c87703-8dcd-4779-837a-9f62c8fc0635)
