### ISSUE TITLE
feat(web): Change button's label

### ISSUE THREAD

**Issue by Helen-Sen** [BinaryStudioAcademy/bsa-2024-bebalance#426]
### What feature?

"To unify the web and mobile versions, change the button label from 'Continue' to 'Start' on the 'Craft your personal Life Balance Wheel!' page."

### Add screenshots

![image](https://github.com/user-attachments/assets/0bc83392-ebfb-4809-95f0-1cf9b1a44173)

**Comment by phoebe-buffay** [comment]
Button name is changed, ticket can be closed
![Image](https://github.com/user-attachments/assets/2be37b81-103f-49ce-9ab5-218a8528ea89)
