### ISSUE TITLE
feat: backend documentation improvement

### ISSUE THREAD

**Issue by KeidsID** [BinaryStudioAcademy/bsa-2024-bebalance#437]
### What feature?

Since our backend endpoints are getting more and more complex, I would like to
improve their documentation.

Such as:

- Grouping endpoints with tags.
- Add more detailed documentation for each endpoint.

### Add screenshots

![Screenshot (388)](https://github.com/user-attachments/assets/35c79da2-c8ea-45c4-bb6f-ee0548ba151b)

**Comment by phoebe-buffay** [comment]
api is categorized
ticket can be closed![Image](https://github.com/user-attachments/assets/868dbb3f-d1ce-4ae4-a27a-8ca617937d1f)
