### ISSUE TITLE
feat: AI Chat service

### ISSUE THREAD

**Issue by anogire** [BinaryStudioAcademy/bsa-2024-bebalance#441]
### What feature?

- [x] Display categories with 3 lowest values.
- [x] Create a service to handle backend chat.
- [x] Add a "Send Request" button (needs to be refined).
- [x] Send request with selected categories and display the received tasks.

### Add screenshots

<img width="184" alt="Screenshot 2024-09-15 at 19 13 29" src="https://github.com/user-attachments/assets/76143b24-b8bb-4639-b763-0b7ab564c49a">

**Comment by KotenkoNata** [comment]
Details of how it looks and works can be found in the description to [PR](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/pull/570)
