### ISSUE TITLE
feat: Popup on the Settings screen when user leaves the page without saving 

### ISSUE THREAD

**Issue by phoebe-buffay** [BinaryStudioAcademy/bsa-2024-bebalance#465]
### What feature?

When user is on Settings page and makes some changes, then doesn't click on Save Changes and decided to leave the page.

1. if user wants to leave exactly the Settings page and remain inside the app, the custom popup should appear (example below)
- popup should have close icon in the up right corner so user can close the popup
- if user clicks on Yes, the changes are not saved and user is relocated to the desired page
- if user clicks on Cancel, user remains on Settings page and can make other changes and save them manually 
![Screenshot 2024-09-13 at 11 54 21 copy](https://github.com/user-attachments/assets/2a4fad90-55fc-44f4-844a-ea44e947fa3f)

3. if user wants to refresh or close the tab with the app, then the browser default popup should appear. 
<img width="264" alt="Screenshot 2024-09-17 at 15 07 07" src="https://github.com/user-attachments/assets/9f0efac1-5713-4f1e-bb2a-81c76ff2ba48">

**Comment by MaxKorop** [comment]
Do we need a close icon at the up-right corner? Because the user can already close the popup with the cancel button

**Comment by phoebe-buffay** [comment]
yes, we need it. it was discussed in the internal chat. user should have the ability to close the popup

**Comment by Helen-Sen** [comment]
1) When the user is on the Settings page and makes some changes, then clicks on "Save Changes" button and decides to leave the page, the Popup message appears. But this popup should appear only if the user leaves the page without saving changes. 
2) When the user clicks "yes" on the Popup message (so the user doesn't want to save changes), goes to another page, and then comes back, he can see that changes were saved.

https://github.com/user-attachments/assets/41df9fa0-2a6a-4bf8-8432-e0f9965b5817
