### ISSUE TITLE
fix: Remove popup when user tries to navigate throughout the the app

### ISSUE THREAD

**Issue by phoebe-buffay** [BinaryStudioAcademy/bsa-2024-bebalance#469]
### Describe your issue

When user clicks on Sign out and navigates throughout the app, the popup remains.

### Steps to reproduce

1. Enter your account
2. Click on Sign Out - popup has appeared
3. Navigate throughout the app using the browser back button
4. Observe the result

### What was the actual result?

The popup remains on the screen although the screens are changed on the background

https://github.com/user-attachments/assets/93e2de7c-5f2b-4135-b821-00330a4daedf

### What was the expected result?

The popup should disappear when user navigates throughout the app

### What OS are you seeing the problem on?

MacOS

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

**Comment by luiqor** [comment]
Bug seems to be already fixed in other ticket
(Windows; both deployed site and latest local main)

https://github.com/user-attachments/assets/af137020-963e-4cb3-a54b-a442360aba69

**Comment by phoebe-buffay** [comment]
yes, it's correct, the issue is not already replicated. the ticket can be closed
