### ISSUE TITLE
fix: Header is seen when user tries to sign out

### ISSUE THREAD

**Issue by phoebe-buffay** [BinaryStudioAcademy/bsa-2024-bebalance#470]
### Describe your issue

When user clicks on sign out and popup appears, the header is seen up on the page

### Steps to reproduce

1. Enter your account
2. Click on Sign Out button
3. Observe the upper part of the screen

### What was the actual result?

The header is seen as active
<img width="1702" alt="Screenshot 2024-09-17 at 16 31 42" src="https://github.com/user-attachments/assets/8f8f3c2c-c1d3-4e56-9433-a34adf1da84c">

### What was the expected result?

The header should be hidden and look like other background - grey

### What OS are you seeing the problem on?

MacOS

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

**Comment by AndriiLevin** [comment]
now it's Ok on Mac Safari. 
<img width="1440" alt="Screenshot 2024-09-21 at 15 34 59" src="https://github.com/user-attachments/assets/6a4d5cce-2088-4b96-937a-f0fbc0e2a7d3">
