### ISSUE TITLE
fix: [Safari] Black screen on the Tasks page

### ISSUE THREAD

**Issue by phoebe-buffay** [BinaryStudioAcademy/bsa-2024-bebalance#474]
### Describe your issue

When user enters the Tasks page, the part of the screen is black

### Steps to reproduce

1. In Safari enter your account
2. Navigate to the Tasks page on the sidebar
3. Observe the result

### What was the actual result?

The part of the screen is black
<img width="1702" alt="Screenshot 2024-09-17 at 17 05 18" src="https://github.com/user-attachments/assets/c123f1e3-bf5c-4a23-973b-dc3c257489ed">

### What was the expected result?

The screen should not be black

### What OS are you seeing the problem on?

MacOS

### What browsers are you seeing the problem on?

Safari

### Severity

Minor (S4)

**Comment by AndriiLevin** [comment]
I tested it on my Mac Safari.
 Now it looks normal.
 
<img width="1440" alt="Screenshot 2024-09-21 at 15 33 19" src="https://github.com/user-attachments/assets/576409b9-7789-45f2-846a-70f013c0a50f">

**Comment by phoebe-buffay** [comment]
yes, correct, issue is not replicated. ticket can be closed
