### ISSUE TITLE
feat:Update the text of the logout confirmation popup 

### ISSUE THREAD

**Issue by MarinaBershova** [BinaryStudioAcademy/bsa-2024-bebalance#477]
### What feature?

Update the text of the logout confirmation popup 

![2024-09-15_17h22_40](https://github.com/user-attachments/assets/9180457a-bd34-4794-8d3f-1c48805e6209)

**Comment by phoebe-buffay** [comment]
please, add dot at the end of the sentence 
![Image](https://github.com/user-attachments/assets/41d9b757-10de-41bf-997a-52f9e130261d)

**Comment by phoebe-buffay** [comment]
issue is fixed, ticket can be closed
<img width="1709" alt="477p" src="https://github.com/user-attachments/assets/1cd05eff-c496-47ab-9235-6c5d4dc042b6">
