### ISSUE TITLE
refactor: Fix issues with quality criterias

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#480]
### What feature?

Our project has been reviewed by other coaches and some code, that doesn't pass quality criteria was found. We need to fix all these issues

1. B22. Bad name
<img width="698" alt="B22-mobile" src="https://github.com/user-attachments/assets/e17f9c77-c422-42f5-8d65-914f5abf5212">

![B22-2-mobile](https://github.com/user-attachments/assets/7d163276-8428-4719-9cb6-11a0020cb191)

2. B28
![B28-mobile](https://github.com/user-attachments/assets/0fe1ce30-1d12-484c-a04a-198d36fa5b97)

3. B22
![B22-mobile-2](https://github.com/user-attachments/assets/015dbdb4-c3f2-4c2f-ac01-4ddbc33e0aaf)
![B22-mobile-3](https://github.com/user-attachments/assets/b629c0c3-0cd1-4d16-9484-ac22f42bdfad)

4. A10
![A10](https://github.com/user-attachments/assets/62fa2f63-fe43-4a75-b8d9-1b274269939f)

**Comment by KotenkoNata** [comment]
Task related to code issues.
