### ISSUE TITLE
feat(web):Add date on the "My wheel results" (root) page 

### ISSUE THREAD

**Issue by Helen-Sen** [BinaryStudioAcademy/bsa-2024-bebalance#494]
### What feature?

According to Figma design, the actual date is displayed on the "My wheel results" (root) page.
But in QA vision the date should be under "My Wheel Results" (as for the mobile version)

### Add screenshots

web design: ![image](https://github.com/user-attachments/assets/4ddb606d-fd8e-491c-ae97-2900eb44e1b0)
mobile design: 
![image](https://github.com/user-attachments/assets/793e53da-284e-4aad-b6d2-08a4c3f103da)

**Comment by fshabanov** [comment]
Is it the current date or the date when the wheel results were updated? @Helen-Sen

**Comment by Helen-Sen** [comment]
It should be the date when the wheel results were updated

**Comment by luiqor** [comment]
Fix:
1. Removed logic that caused issue on different devices:
![image](https://github.com/user-attachments/assets/f1821621-154c-4709-b3f7-7d2494d45778)

2. Modify width of date container to look good with long dates
