### ISSUE TITLE
feat: Text update on the quiz Last Step

### ISSUE THREAD

**Issue by phoebe-buffay** [BinaryStudioAcademy/bsa-2024-bebalance#498]
### What feature?

Text should be updated into the next:
"How often would you like to receive motivational follow-ups?"
![Screenshot 2024-09-18 at 18 33 54 copy](https://github.com/user-attachments/assets/65f63875-7c82-4466-95fe-7d65450e12b4)

**Comment by KeidsID** [comment]
This option may be better:

- Would you like to receive daily motivational follow-ups?
   - [x] Yes, I want to receive daily motivation!
   - [ ] No, I prefer not to receive daily motivational follow-ups.
   
Since it's just a Yes/No question, "How often..." sounds odd.

**Comment by phoebe-buffay** [comment]
yes, you are correct. Please proceed with 
"Would you like to receive daily motivational follow-ups?"
