### ISSUE TITLE
fix: Insights are not updated after user makes actions with tasks

### ISSUE THREAD

**Issue by phoebe-buffay** [BinaryStudioAcademy/bsa-2024-bebalance#561]
### Describe your issue

Insights are not updated after user makes actions with tasks

### Steps to reproduce

1. Go to Tasks
2. Make some actions - skip or make complete
3. go to the Wheel screen
4. Observe insights

### What was the actual result?

Insights are not updated when they should be

https://github.com/user-attachments/assets/4e1bd38d-a8d9-4c12-8ad4-2b251cdedf95

### What was the expected result?

Insights should be updated just after user makes actions with tasks and not after refreshing the page

### What OS are you seeing the problem on?

MacOS

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

**Comment by luiqor** [comment]
- Modify the calculation of completionTasksPercentage to be based only on 'Completed' and 'Current,' as per the results of the requirements discussion
- Immediately update authenticatedUser completionTasksPercentage when they perform a task action.

**Comment by phoebe-buffay** [comment]
issue is fixed
ticket can be closed
https://github.com/user-attachments/assets/1b5948ff-d063-42f5-8494-851091f6f36f
