### ISSUE TITLE
fix: default browser popup when reloading or closing tab everywhere

### ISSUE THREAD

**Issue by MaxKorop** [BinaryStudioAcademy/bsa-2024-bebalance#580]
### Describe your issue

The default browser popup appears everywhere when the user tries to reload the page or close the app tab even if there are no changes

### Steps to reproduce

1. Go to any page
2. Reload page / Close tab

### What was the actual result?

The default browser popup appears

### What was the expected result?

This popup should appear only if there are any changes in the forms

### Put here any screenshots or videos (optional)

![image](https://github.com/user-attachments/assets/465cab59-8091-4c25-8bee-cc3cc57fa551)

### What OS are you seeing the problem on?

Other (mention in the description)

### What browsers are you seeing the problem on?

Other (mention in the description)

### Severity

Critical (S2)

**Comment by phoebe-buffay** [comment]
issue is fixed
ticket can be closed
