### ISSUE TITLE
feat: Settings screen

### ISSUE THREAD

**Issue by anogire** [BinaryStudioAcademy/bsa-2024-bebalance#599]
### What feature?

- [x] Add last Quiz screen
- [x] Sign out button should still be present on the screen

### Add screenshots

<img width="456" alt="Screenshot 2024-09-26 at 18 12 10" src="https://github.com/user-attachments/assets/7db0ae62-c45b-4fe3-a969-f82135c68ca0">

**Comment by KotenkoNata** [comment]
For the web version, we have 

![Image](https://github.com/user-attachments/assets/c760aa55-0371-4094-a40d-d8f8b7a20104)

I create. Do I need to add a Save button?

 ![Image](https://github.com/user-attachments/assets/3d4b3a4c-108d-4b0d-b028-1bf086a5f09f)

**Comment by anogire** [comment]
Yes, I think we need a button to save the changes.
I missed that in the description.

**Comment by KotenkoNata** [comment]
Details can be found in the description to [PR](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/pull/602#issue-2552310845) 

The final version has a slightly different appearance.

**Comment by KotenkoNata** [comment]
Correct title for Setting screen in [issue](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/pull/620#issue-2554092263)
