### ISSUE TITLE
feat(mobile):User's avatar should have a circular form

### ISSUE THREAD

**Issue by Helen-Sen** [BinaryStudioAcademy/bsa-2024-bebalance#603]
### What feature?

The avatar displayed for the user should have a circular shape to maintain consistency with the web version

### Add screenshots

web: 
![image](https://github.com/user-attachments/assets/a5b7a478-a68f-4828-948e-640e1ca0f98a)
mobile: 
![image](https://github.com/user-attachments/assets/2fa0bac2-8d67-4f5c-bb43-9288298f295c)

**Comment by revenets** [comment]
@Helen-Sen Please, provide the user credentials to reproduce this issue

**Comment by Helen-Sen** [comment]
email: iamtrueolena@gmail.com
password: Helena12

**Comment by KotenkoNata** [comment]
Fixed. Details in [PR](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/pull/607#issue-2552467931)
