### ISSUE TITLE
fix: The insights percentage doesn't represent correct progress

### ISSUE THREAD

**Issue by phoebe-buffay** [BinaryStudioAcademy/bsa-2024-bebalance#605]
### Describe your issue

The insights percentage doesn't represent correct progress

### Steps to reproduce

1. Receive tasks from the AI
2. Complete them
3. Observe the Insights percentage with every completed task

### What was the actual result?

The 50% and 89% (as example) doesn't look on the scale as these recents - 50% shows on scale more then 50%; 89% look like 100%

### What was the expected result?

The percentage and scale should correspond each other and show correct level

### Put here any screenshots or videos (optional)

![Screenshot 2024-09-27 at 09 56 05](https://github.com/user-attachments/assets/6338b397-50a9-4b8c-880a-ede16f41dc40)
<img width="1709" alt="Screenshot 2024-09-27 at 11 02 35" src="https://github.com/user-attachments/assets/ac3df7a4-14f4-4217-8ef5-008fb7294cfc">

### What OS are you seeing the problem on?

MacOS

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

**Comment by Helen-Sen** [comment]
![image](https://github.com/user-attachments/assets/5eb1725d-cfb0-42b7-9f4a-991ac5a9704c)
![image](https://github.com/user-attachments/assets/adb812fb-6d69-4662-8d0d-aec03cb229ff)
