### ISSUE TITLE
fix(mobile):When a user sings out of the application, he is directed to the Sign in screen and periodically sees an error message "You are unauthorized to access the requested resource"

### ISSUE THREAD

**Issue by Helen-Sen** [BinaryStudioAcademy/bsa-2024-bebalance#608]
### Describe your issue

When a user signs out of the application, he is directed to the Sign in screen and periodically (not every time) sees an error message "You are unauthorized to access the requested resource"

### Steps to reproduce

1. Open the app
2. Sign in with exciting user (email: iamtrueolena@gmail.com, password: Helena12)
3. Go to the "Settings" screen and tap "Sign out" button
4. Observe the "Sign in" screen

### What was the actual result?

When a user signs out of the application, he is directed to the Sign in screen and periodically (not every time) sees an error message "You are unauthorized to access the requested resource"

### What was the expected result?

When a user signs out of the application, he is directed to the Sign in screen and he doesn't see any message

### Put here any screenshots or videos (optional)

![image](https://github.com/user-attachments/assets/1d3381a4-639c-412e-8ff2-86d2c029c315)

https://github.com/user-attachments/assets/b67f2bd4-eb8f-4803-824a-3945b84c6172

### What OS are you seeing the problem on?

Android

### Severity

Minor (S4)

**Comment by KotenkoNata** [comment]
Problem with error - You are unauthorized to access the requested resource fixed in [issue](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/pull/615#issue-2553202918) 

https://github.com/user-attachments/assets/5490efd8-f101-48a6-afe5-686d552b73fc

https://github.com/user-attachments/assets/98ec6428-9390-4ef8-962a-8a611fa43d03
