### ISSUE TITLE
Create section 6 and 7 of Test Strategy

### ISSUE THREAD

**Issue by MarinaBershova** [BinaryStudioAcademy/bsa-2024-bebalance#63]
### What feature?

Create section 6 - "Additional procedures".
Identify actions to improve the testing process and QA team responsibilities.

Create section 7 - "Common risks".
Identify risks, responsible persons and actions necessary to resolve the arisen risks.

https://docs.google.com/document/d/1fkKAXoTv2ud860wz_SC717khTmcm0-XKf4kvg2iX0fg/edit

**Comment by StanislavHorkusha** [comment]
Left comments under your sections, definitely involve the QA team in the discussion. Answer to comments after fixing
