### ISSUE TITLE
Create section 1 of Test Strategy

### ISSUE THREAD

**Issue by LiudmylaPerev** [BinaryStudioAcademy/bsa-2024-bebalance#64]
### What feature?

Create section 1 - "Introduction"

1. The purpose of the test strategy for the BeBalance
2. Analogues
3. Used technologies
4. Documents
5. Project team
6. Project deadlines
7. Communications approach

https://docs.google.com/document/d/1fkKAXoTv2ud860wz_SC717khTmcm0-XKf4kvg2iX0fg/edit

**Comment by StanislavHorkusha** [comment]
Left small comments in the file, overall it's fine, good job
