### ISSUE TITLE
Create section 4, 5 of the Test Strategy

### ISSUE THREAD

**Issue by phoebe-buffay** [BinaryStudioAcademy/bsa-2024-bebalance#65]
Section 4: Testing Tools and Artifacts
Section 5: Release Control

**Comment by StanislavHorkusha** [comment]
Added comments, please resolve issues and reply to all comments [here](https://docs.google.com/document/d/1fkKAXoTv2ud860wz_SC717khTmcm0-XKf4kvg2iX0fg/edit) under your sections
