### ISSUE TITLE
Create requirements for Sign in page

### ISSUE THREAD

**Issue by MarinaBershova** [BinaryStudioAcademy/bsa-2024-bebalance#66]
### What feature?

Create requirements for:

- Email field
- Password field
- Sign in button
https://docs.google.com/document/d/1meay2RZ2EydQ3jVEeoqWI9H80ZyL4pOKOznmmbugzRE/edit#heading=h.52kerqychhs6

![Image](https://github.com/user-attachments/assets/485cdbd5-ada4-4293-aee2-cbe2d7101f00)

**Comment by StanislavHorkusha** [comment]
Left some comments please review and fix

**Comment by IrynaPermiakova** [comment]
@MarinaBershova 
regarding the fields validation requirements, wait for the "sign up" approval to avoid disagreements
