### ISSUE TITLE
feat: Clean up

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#69]
### What feature?

- [x] Remove `loadAll` action from users module in frontend
- [x] Remove endpoint for loading all users
- [x] Clean redundant components from the root view

**Comment by fshabanov** [comment]
It means removing the links, that we have, not exactly sure which file. We have some links to sign in, sign up

**Comment by phoebe-buffay** [comment]
it was refactoring, ticket can be closed
