### ISSUE TITLE
feat: Sign In

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#7]
- [ ]  Sign in form
- [ ]  Sign in action flow
- [ ]  Add user to redux store
- [ ]  Validation (shared)
- [ ]  Design
- [ ]  "Create an account" link should navigate to the sign up page

![image](https://github.com/user-attachments/assets/0388b395-a4c7-49c0-b092-955c63ab654b)

**Comment by phoebe-buffay** [comment]
Please, fix these issues:
1. Sign in action flow - at this point user is not relocated to the next page after clicking on sign in button. User should be redirected to the next page which is Onboarding questions
2. Sign in font size is incorrect. Now it's 28, and should be according to Figma 24
![Image](https://github.com/user-attachments/assets/719c1ba0-bcb6-461e-a9d1-83fed90b1c24)
3. The space between "No account ..." and Email field is smaller than in Figma. Please adjust. 
![Image](https://github.com/user-attachments/assets/0d981fd2-4fd4-4217-96c7-53be0bcfa694)
4. Forgot password button is absent. Please add this button
![Image](https://github.com/user-attachments/assets/270ccbfa-f32c-4eb9-80b6-17224550f629)

**Comment by phoebe-buffay** [comment]
5. White dots are absent on the right side of the screen. They are present in Figma design
<img width="1700" alt="7 4" src="https://github.com/user-attachments/assets/3475e0ca-3046-40da-b70c-38fdf300814b">
<img width="1700" alt="7 5" src="https://github.com/user-attachments/assets/1614a0a8-0d8f-47e1-828b-2dcbdf1d7568">

**Comment by phoebe-buffay** [comment]
1. Sign in action flow - at this point user is not relocated to the next page after clicking on sign in button. User should be redirected to the next page which is Onboarding questions  -  issue is fixed, user is relocated to the root p[age for now as was discussed
2. Sign in font size is incorrect. Now it's 28, and should be according to Figma 24 - issue is fixed 

![Image](https://github.com/user-attachments/assets/1e085d51-8b89-4f42-b688-6f077413f845)


3. The space between "No account ..." and Email field is smaller than in Figma. Please adjust. - issue is fixed

![Image](https://github.com/user-attachments/assets/6d256cb0-6e28-42a3-bc79-a8cfaac3fdac)


4. Forgot password button is absent. Please add this button - issue is present

![Image](https://github.com/user-attachments/assets/83e26a15-94c1-4ca3-b120-07282f7417cf)


5. White dots are absent on the right side of the screen. They are present in Figma design - issue is fixed

![Image](https://github.com/user-attachments/assets/c28bdacd-19b8-429c-b3bc-549613a0f075)

**Comment by JD-Rosales** [comment]
> 1. Sign in action flow - at this point user is not relocated to the next page after clicking on sign in button. User should be redirected to the next page which is Onboarding questions  -  issue is fixed, user is relocated to the root p[age for now as was discussed
> 2. Sign in font size is incorrect. Now it's 28, and should be according to Figma 24 - issue is fixed
> 
> ![Image](https://private-user-images.githubusercontent.com/86659067/363625855-1e085d51-8b89-4f42-b688-6f077413f845.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjc5MzAsIm5iZiI6MTcyNTI2NzYzMCwicGF0aCI6Ii84NjY1OTA2Ny8zNjM2MjU4NTUtMWUwODVkNTEtOGI4OS00ZjQyLWI2ODgtNmYwNzc0MTNmODQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA5MDAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMTRjNDY5MWRhZWE4Yjg0NzU1NjliZTU4NmUyNTI3ODc3ZjFmMTIxMDhlM2RhMmIyMWZkOWI3NjY0OTUxNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VU4IDyYyHNj5typxWn0MM8QsdaDg93WqCe9i6iZn9Po)
> 
> 3. The space between "No account ..." and Email field is smaller than in Figma. Please adjust. - issue is fixed
> 
> ![Image](https://private-user-images.githubusercontent.com/86659067/363625910-6d256cb0-6e28-42a3-bc79-a8cfaac3fdac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjc5MzAsIm5iZiI6MTcyNTI2NzYzMCwicGF0aCI6Ii84NjY1OTA2Ny8zNjM2MjU5MTAtNmQyNTZjYjAtNmUyOC00MmEzLWJjNzktYThjZmFhYzNmZGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA5MDAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhY2Y5YjhmMGQ3ZGY1MGFhYmIxNjEwMWE4YWM0MjlkNzMyYWFkMzFjZDEzNzUwYzM4NDc3OWQxNDU0YWZlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jv0212_3s0tOtsksklorb9inSF3lUFIEKVl9ruSsRQA)
> 
> 4. Forgot password button is absent. Please add this button - issue is present
> 
> ![Image](https://private-user-images.githubusercontent.com/86659067/363626048-83e26a15-94c1-4ca3-b120-07282f7417cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjc5MzAsIm5iZiI6MTcyNTI2NzYzMCwicGF0aCI6Ii84NjY1OTA2Ny8zNjM2MjYwNDgtODNlMjZhMTUtOTRjMS00Y2EzLWIxMjAtMDcyODJmNzQxN2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA5MDAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiOGVjNDhmZmFlNGUzZjI0ZDVmYTg2OGMyMDUwYmYyOTU4Njg3M2Q0OWYzYWRmNDY3ZWE4YjI4M2FjOTM0NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bAxxDwfBI1I1txoNdpXBYEOIK57MmCUf0oYnOrpqR7s)
> 
> 5. White dots are absent on the right side of the screen. They are present in Figma design - issue is fixed
> 
> ![Image](https://private-user-images.githubusercontent.com/86659067/363626078-c28bdacd-19b8-429c-b3bc-549613a0f075.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjc5MzAsIm5iZiI6MTcyNTI2NzYzMCwicGF0aCI6Ii84NjY1OTA2Ny8zNjM2MjYwNzgtYzI4YmRhY2QtMTliOC00MjljLWIzYmMtNTQ5NjEzYTBmMDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA5MDAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NDkxM2NhNTE2NmM4M2ZhNGU5MDE2NjhlYjBlYTE4Yjc1Zjc2YThjNWZhZjlkMzcyMWMxNTU3MWVjZTFkMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZmpYKePXL6-H2EAq1hARkuNOhRZ4pysfY8sI6T3yQ8Q)

Currently, the forgot password functionality is being implemented by @ihorLysak PR #230.

**Comment by phoebe-buffay** [comment]
ok, then the ticket can be closed
