### ISSUE TITLE
feat: Sign Up

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#8]
- [x]  Model (get user)
- [x]  Service (sign-up flow)
- [x]  Controller (sign-up endpoint)
- [x]  Encrypt user password
- [x]  Return user to the client
- [x]  Validation (shared)
- [x]  Unique email

**Comment by phoebe-buffay** [comment]
1. in user model there is no Name field, although it's required for signing up, so user can't register the account
![Image](https://github.com/user-attachments/assets/31daffec-624f-41fc-8de2-132c5f1311bf)
2. user is able to register account without password. 
If "password": "" - the registration is passed and user is created
if field Password is completely absent - then the error appears

**Comment by luiqor** [comment]
> 1. in user model there is no Name field, although it's required for signing up, so user can't register the account

- [ ] update swagger documentation for /auth/sign-up endpoint

> 2. user is able to register account without password.
>    If "password": "" - the registration is passed and user is created
>    if field Password is completely absent - then the error appears

The issue of minimum password validation requirement has been decided to be addressed in a separate ticket  along with other validation requirements.

**Comment by phoebe-buffay** [comment]
user is able to register - name string is present
![Image](https://github.com/user-attachments/assets/035802ab-f45f-444d-8bbc-ca95b9d5391a)

name is present in the user schema
![Image](https://github.com/user-attachments/assets/474e38dc-14b3-41d2-ac8b-d9b858dcd9c0)
