### ISSUE TITLE
feat: Quiz Entry screen

### ISSUE THREAD

**Issue by anogire** [BinaryStudioAcademy/bsa-2024-bebalance#80]
### What feature?

- [x] Create Quiz entry screen using the styles and components we've already created.

### Add screenshots

![Screenshot 2024-08-20 at 16 48 41](https://github.com/user-attachments/assets/0319968d-b3b5-4a32-9103-03f3ae7a0d4f)

**Comment by MarinaBershova** [comment]
Paddings on emulator are different from paddings on mockup in Figma
In Figma:
![Image](https://github.com/user-attachments/assets/c5372921-2d9e-4d03-b3c7-3d2697e6a33f)

On emulator:
![Image](https://github.com/user-attachments/assets/1e7c247e-1d0d-437d-880c-75dacff3f2a2)

**Comment by MarinaBershova** [comment]
Paddings have been increased


![Image](https://github.com/user-attachments/assets/6ba4d501-4fe8-4542-8a39-bda34614ea4e)
