### ISSUE TITLE
feat: Quiz question component

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#88]
### What feature?

- [ ] Add a quiz question component

### Add screenshots

![image](https://github.com/user-attachments/assets/20d00f85-584f-46ac-8227-066943f86a1c)

**Comment by MarinaBershova** [comment]
Need to add gradient for selected radio buttons


![Image](https://github.com/user-attachments/assets/c153906a-3956-4be1-b1ec-07af85da7886)

like in Figma
![Image](https://github.com/user-attachments/assets/10177df2-e8d0-4bab-bb9b-eca5ced7c95a)
