### ISSUE TITLE
feat: Sign Up

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#9]
- [x]  Form
- [x]  Sign up action flow
- [x]  Add user to the redux store
- [x]  Validation (shared)
- [x]  Design
- [x]  Sign in link should navigate to sign in page

![image](https://github.com/user-attachments/assets/ccb1b5eb-08fa-4295-a829-7f9c5ffa796c)

**Comment by phoebe-buffay** [comment]
Please, fix these issues:
1. Sign up action flow - user at this point is not relocated to the next page after clicking on Create an account. User should be relocated to the next page which is Onboarding questions according to the Figma
2. Instead "Sign Up" there should be  "CREATE AN ACCOUNT" according to Figma
![Image](https://github.com/user-attachments/assets/40111881-0188-47df-a7b9-117f49fe7af9)
3. The space between "Already have an account ..." and Name field is smaller than in Figma. Please adjust.
![Image](https://github.com/user-attachments/assets/10a8e561-847b-4ab3-9a10-45181907c3c3)
4. The font size of the CREATE AN ACCOUNT text should be 24 according to the Figma. Now it's 28
![Image](https://github.com/user-attachments/assets/9f6fb483-adf7-4338-ab4b-bd309352f0ea)
5. There are no white dots in the right side of the screen as it is in design
![Image](https://github.com/user-attachments/assets/de2dbd56-ee2c-4381-8869-cd38c3196ee5)
![Image](https://github.com/user-attachments/assets/a80f97e2-4e0a-49f3-ae4a-4a7e34aa930a)
6. In Sign in text "In" should start from upper case
![Image](https://github.com/user-attachments/assets/b11ddf54-efbb-4a90-b40d-815204cf72ba)

**Comment by phoebe-buffay** [comment]
1. Sign up action flow - user at this point is not relocated to the next page after clicking on Create an account. User should be relocated to the next page which is Onboarding questions according to the Figma - issue is fixed, user is relocated to the home page which is root for now
2. Instead "Sign Up" there should be "CREATE AN ACCOUNT" according to Figma - issue is fixed

![Image](https://github.com/user-attachments/assets/9a25b8ac-d80e-4e1b-82eb-e9748165375e)


3. The space between "Already have an account ..." and Name field is smaller than in Figma. Please adjust.- issue is fixed

![Image](https://github.com/user-attachments/assets/c6447ba6-ab5b-4cea-95e3-92a20b17512b)


4. The font size of the CREATE AN ACCOUNT text should be 24 according to the Figma. Now it's 28 - issue is fixed

![Image](https://github.com/user-attachments/assets/943c8897-e254-48d3-a85e-198aeac034ae)


5. There are no white dots in the right side of the screen as it is in design - issue is fixed

![Image](https://github.com/user-attachments/assets/e65c64df-4337-4c8e-8378-84c7fac2341f)


6. In Sign in text "In" should start from upper case - issue is fixed

![Image](https://github.com/user-attachments/assets/b30d62ff-815b-43da-84e1-4ee7cf53ba2d)
