### ISSUE TITLE
feat: Header component

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#91]
### What feature?

- [x] Create Header component
- [x] No need to add chat icon and dropdown icon
- [x] Avatar should be a default one

### Add screenshots

![Header](https://github.com/user-attachments/assets/6d1d7815-5688-47ee-9a95-5f96db2e0b12)

**Comment by LiudmylaPerev** [comment]
closed, but create bug because according to figma  the logo and avatar are on the same line (sidebar(logo) and avatar were implemented by different people)
